### ISSUE TITLE
[BUG][ENHANCMENT] Add suport for non-chromium browsers

### ISSUE THREAD

**Issue by HPaulson** [milasoftwaregroup/imago#6] opened 2020-04-24 23:56 UTC
**Proposal**
Allow imago support on browsers that are NOT chromium based.

**Why?**
This would be an extreme enhancement to Imago, and should've been implemented in the first place, so much though that it's a bug. Currently, Logging in the Imago only works on Chromium-based Desktop Browsers, Tested on **Edge**, **Chrome**, and **Chromium**, FireFox Developer Edition, Firefox, Safari, Safari Mobile, Chrome Mobile IOS, FireFox Mobile IOS. You may notice, all of the bold browsers are Chromium-based Desktop browsers. This is a major downside to Imago for a few reasons:

1. Creates a large struggle for Linux users, as many use FireFox (As it's stock, and better supported)
2. Is simply stupid. Supporting only a select few browsers is extremely restrictive, and leaves many users forced to use a browser they wouldn't otherwise use, just to have Imago. This could cause many users to not use the platform, due to the hassle of moving from their favorite browser. This enhancement would give Imago much more support for browsers and users, and would most likely contribute to the popularity of the project!

**What occurs? What should occur?**
Currently, attempting to login on a non-Chromium-based browser causes the site to simply refresh. When pressing the login button (And/or pressing enter) the site simply refreshes, and will not log in. The expected result is that the site will log the user in like normal, and that it would support many more popular-browsers.

**Comment by advilm** [comment] 2020-04-25 00:24
Signing into imago on Firefox works fine for me.

**Comment by HPaulson** [comment] 2020-04-25 00:56
> Signing into imago on Firefox works fine for me.

Definitely cannot reproduce this. For a split second i receive the red "Invalid username or password" message, when indeed these are my correct credentials, and copying them to Edge works just fine. Here's a video of what is occurring:

[Video](https://cdn.smc.wtf/i/ViMukm2v.mp4)

**Comment by Jack-Gledhill** [comment] 2020-04-25 08:44
I'd class this is a top-priority bug. If any information can be provided to help me debug this, I'd appreciate it.

It appears that the bug seems to be only partly reproducible, this makes it incredibly hard for me to debug.

**Comment by Jack-Gledhill** [comment] 2020-04-25 09:23
Issue supposedly fixed as of [148ce12](https://github.com/milasoftwaregroup/imago/commit/148ce12d43c2c070cb927957f56008531e157af0). If the bug persists or a similar bug arises, please submit a new issue.

**Closed as completed by Jack-Gledhill** 2020-04-25 09:23 UTC
Labels: bug, enhancement
